name = "openid-connect"
main = "./build/worker.mjs"
compatibility_date = "2024-04-15"

[[kv_namespaces]]
binding = "openid-connect"
id = "4108843e6d19454eafc175b58aae9a49"

[build]
command = "make build"
