openapi: 3.0.3
info:
  title: OpenID Connect APP
  description: |-
    This is the OpenID Connect API documentation.
  termsOfService: https://localhost:8787
  contact:
    email: kotaro.otaka@example.com
  license:
    name: MIT
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8787
tags:
  - name: OIDC
    description: OIDC
  - name: IdP
    description: IdP
paths:
  /.well-known/openid-configuration:
    get:
      tags:
        - OIDC
      summary: OpenID Provider Configuration
      description: OpenID Provider Configuration
      operationId: openIDConfiguration
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OpenIDConfigurationResponseSchema"
        default:
          description: Internal Server Error
  /authorize:
    get:
      tags:
        - OIDC
      summary: Authorization Endpoint
      description: |
        Authorization Endpoint
        ref: https://openid-foundation-japan.github.io/rfc6749.ja.html#code-authz-req
      operationId: authorize
      parameters:
        - name: response_type
          in: query
          required: true
          description: response_type
          schema:
            type: string
            enum:
              - code
        - name: client_id
          in: query
          required: true
          description: client_id
          schema:
            type: string
            format: uri
            example: http://localhost:8080
        - name: redirect_uri
          in: query
          required: false
          description: http://localhost:8080/callback
          schema:
            type: string
            format: uri
            example: http://localhost:8080/callback
        - name: scope
          in: query
          required: false
          description: openid
          schema:
            type: string
            enum:
              - openid
        - name: state
          in: query
          required: false
          description: state
          schema:
            type: string
      responses:
        "302":
          description: Found
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: http://localhost:8080/callback
        default:
          description: Internal Server Error
  /login:
    get:
      tags:
        - IdP
      summary: Login Veiw
      description: Login View
      operationId: loginView
      parameters:
        - name: id
          in: query
          required: true
          description: id
          schema:
            type: string
            example: xxxxxxxxxx
      responses:
        "200":
          description: OK
          content:
            text/html:
              schema:
                type: string
        default:
          description: Internal Server Error
    post:
      tags:
        - IdP
      summary: Login
      description: Login
      operationId: login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: xxxxxxxxxx
                password:
                  type: string
                  example: xxxxxxxxxx
      responses:
        "302":
          description: Found
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: http://localhost:8787/authorize?response_type=code&client_id=http://localhost:8080&redirect_uri=http://localhost:8080/callback&scope=openid&state=xxxxxxxxxx
        default:
          description: Internal Server Error
  /callback:
    get:
      tags:
        - IdP
      summary: Callback
      description: Callback
      operationId: callback
      parameters:
        - name: id
          in: query
          required: true
          description: id
          schema:
            type: string
            example: xxxxxxxxxx
      responses:
        "302":
          description: Found
          headers:
            Location:
              schema:
                type: string
                format: uri
                example: http://localhost:8080/callback
        default:
          description: Internal Server Error
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    OpenIDConfigurationResponseSchema:
      type: object
      properties:
        issuer:
          type: string
          description: http://localhost:8787
          format: uri
          example: http://localhost:8787
        authorization_endpoint:
          type: string
          description: http://localhost:8787/authorize
          format: uri
          example: http://localhost:8787/authorize
        token_endpoint:
          type: string
          description: http://localhost:8787/token
          format: uri
          example: http://localhost:8787/token
        userinfo_endpoint:
          type: string
          description: http://localhost:8787/userinfo
          format: uri
          example: http://localhost:8787/userinfo
        jwks_uri:
          type: string
          description: http://localhost:8787/certs
          format: uri
          example: http://localhost:8787/certs
        revocation_endpoint:
          type: string
          description: http://localhost:8787/revoke
          format: uri
          example: http://localhost:8787/revoke
      required:
        - issuer
        - authorization_endpoint
        - token_endpoint
        - userinfo_endpoint
        - jwks_uri
        - revocation_endpoint
