openapi: 3.0.3
info:
  title: OpenID Connect APP
  description: |-
    This is the OpenID Connect API documentation.
  termsOfService: https://localhost:8787
  contact:
    email: kotaro.otaka@example.com
  license:
    name: MIT
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8787
tags:
  - name: OIDC
    description: OIDC
paths:
  /.well-known/openid-configuration:
    get:
      tags:
        - OIDC
      summary: OpenID Provider Configuration
      description: OpenID Provider Configuration
      operationId: openIDConfiguration
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenIDConfigurationResponseSchema'
        default:
          description: Internal Server Error
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    OpenIDConfigurationResponseSchema:
      type: object
      properties:
        issuer:
          type: string
          description: http://localhost:8787/op
          format: uri
          example: http://localhost:8787/op
        authorization_endpoint:
          type: string
          description: http://localhost:8787/op/authorize
          format: uri
          example: http://localhost:8787/op/authorize
        token_endpoint:
          type: string
          description: http://localhost:8787/op/token
          format: uri
          example: http://localhost:8787/op/token
        userinfo_endpoint:
          type: string
          description: http://localhost:8787/op/userinfo
          format: uri
          example: http://localhost:8787/op/userinfo
        jwks_uri:
          type: string
          description: http://localhost:8787/op/certs
          format: uri
          example: http://localhost:8787/op/certs
        revocation_endpoint:
          type: string
          description: http://localhost:8787/op/revoke
          format: uri
          example: http://localhost:8787/op/revoke
      required:
        - issuer
        - authorization_endpoint
        - token_endpoint
        - userinfo_endpoint
        - jwks_uri
        - revocation_endpoint
